### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by Chilinot** [brian-watkins/elmer#2]
What are the plans for supporting Elm 0.19? I saw the `elm-19` branch, but couldnt see info in regards to the status of it, is it usable, or is it merely testing if its possible?

**Comment by brian-watkins** [comment]
The code in the `elm-19` branch works with Elm 0.19 (all the tests pass), but I still need to figure out a good way for folks to install Elmer as a test dependency for an Elm 0.19 application (so someone can actually use it to write tests for their code). I'm also adding a few more features before I'm ready for a release.

**Comment by brian-watkins** [comment]
You can now use the latest version of Elmer (4.0.0) with Elm 0.19. Just follow the instructions from the README. I'd appreciate any feedback.
